name: streamlit
channels:
- conda-forge
dependencies:
- python=3.7  # keep at python 3.7
- numpy=1.18.1
- pandas=1.0.3
- matplotlib=3.2.1
- scipy=1.4.1
- altair=4.1.0
- wordcloud=1.7.0
- plotly=4.7.1
- pip  # don't pin this version, we always want latest
- pip:
  - streamlit
  - nltk
 